package code.excursion.cms;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chris
 */
public enum ConfigurationEnum {
  PROJECT, VERSION, BASE_DIR, CODE_DIR, THEME_DIR,
  TEMPLATE_BASE, TEMPLATE_LIFERAY_BASE, TEMPLATE_TOMCAT_BASE, TEMPLATE_TOMCAT_EXT, TEMPLATE_LIFERAY_ROOT_DIR, TEMPLATE_LIFERAY_ROOT_CLASSES_DIR,
  TEMPLATE_TOMCAT_BIN, TEMPLATE_TOMCAT_CONF, TEMPLATE_LIFERAY_DEPLOY_DIR, TEMPLATE_LIFERAY_ROOT_LOGGING_DIR,
  CONFIG_TEMPLATE_BASE, CONFIG_TEMPLATE_TOMCAT_BASE, CONFIG_TEMPLATE_TOMCAT_BIN, CONFIG_TEMPLATE_TOMCAT_CONF, CONFIG_TEMPLATE_LIFERAY_BASE,
  CONFIG_TEMPLATE_LIFERAY_DEPLOY_DIR,
  LOCAL_DEPLOY_DIR, DSL_DEPLOY_DIR, DSL_MEDIA_DIR, DSL_SUPPORT_DIR, DSL_INSTALL_DIR,
  excursion_SHARED_TARGET, R2D2_TARGET, GLOBAL_PARAMETERS_TARGET, CARD_CATALOG_TARGET, LEMA_TARGET, WEB_SERVICE_CLIENTS_DIR,
  JAVA_SECURITY_DIR, PROVIDED_DIR, PROVIDED_DDL_FILE_DIR, PROVIDED_JARS_DIR, PROVIDED_EHCACHE_DIR, PROVIDED_ROOT_FILE_DIR,
  PROVIDED_BIN_DIR, PROVIDED_CONF_DIR, PROVIDED_PORTAL_EXT_DIR, PROVIDED_LICENSE_DIR, PROVIDED_SUPPORT_DIR, PROVIDED_INSTALL_DIR,
  PROVIDED_SOLR_FILE_DIR, PROVIDED_LIFERAY_LOGGING_DIR,
  FILES_TO_DEPLOY, FILES_TO_DEPLOY_COUNT, 
  LIFERAY_UNMODIFIED_DIR, LIFERAY_MODIFIED_DIR, LIFERAY_APPS_DIR, DDL_LPKG_FILE_NAME, DDL_WAR_FILE_NAME, LIFERAY_APPS_NEW_DIR, LIFERAY_SANDBOX_LPKG_DIR,
  LIFERAY_SANDBOX_WAR_DIR, SOLR_LPKG_FILE_NAME, SOLR_WAR_FILE_NAME, INSTALL_SCRIPT_DIR, INSTALL_SCRIPT_TEMPLATE_DIR, INSTALL_SCRIPT_FILE_NAME,
  APACHE_ANT_FILE, LIFERAY_SANDBOX_DIR,
  JAR_EXTENSION, WAR_EXTENSION
  
  ;
}
